min_version = "2024.9.5"

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[settings]
python.uv_venv_auto = true

[tools]
python = "3.13"
ruff = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv sync"

[tasks.run]
alias = "r"
description = "Run the application"
run = "python main.py"

[tasks.GUI]
alias = "g"
description = "Run the GUI"
run = "python GUI/main.py"

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''
